version: "3.7"

services:
    web:
        build:
            context: ./frontend
            dockerfile: ../files/frontend.Dockerfile
        command: yarn start
        volumes: 
            - ./frontend:/app
        ports: 
            - 3000:3000
        
    backend:
        build: 
            context: ./backend
            dockerfile: ../files/backend.Dockerfile
        command: python manage.py runserver 0.0.0.0:8000
        volumes: 
            - ./backend:/opt/app
        ports: 
            - 8000:8000
        env_file: 
            - ./files/.env.dev
            - ./files/.secret
    db:
        image: postgres:12.0-alpine
        volumes:
           -  postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=pass
            - POSTGRES_DB=db
    rabbit:
        container_name: rabbitmq
        hostname: rabbit
        image: rabbitmq:3
        ports: 
            - "5672:5672"
    celery:
        build: 
            context: ./backend
            dockerfile: ../files/backend.Dockerfile
        command: celery -A backend worker -l INFO
        volumes: 
            - ./backend:/opt/app
        env_file: 
            - ./files/.env.dev
            - ./files/.secret
        depends_on: 
            - rabbit
        links:
            - rabbit
    flower:  
        image: mher/flower
        environment:
            - CELERY_BROKER_URL=amqp://rabbitmq//
            - FLOWER_PORT=8888
        ports:  
            - 8888:8888
      
volumes:
    postgres_data: