# Generated by Django 3.2.5 on 2021-07-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alt_text", models.CharField(max_length=1000)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("temp_file", models.FileField(upload_to="uploads/")),
                ("s3_url", models.CharField(max_length=256)),
            ],
        ),
    ]
