# Generated by Django 3.2.5 on 2021-07-18 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
        ("photos", "0003_auto_20210718_1008"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="posts.post",
            ),
        ),
    ]
